-- =============================================================================
-- species_traits: clasificación conductual por especie (functional_name)
-- Fuente: cluster_to_create_traits.csv (ltem_report/data/, 125 especies)
-- Generado para: ChatMPA-Studio/chatmpa-skills#27
-- =============================================================================
-- Nota: functional_name = 'Pelagic' (12 sp.) se almacena aquí pero se excluye
-- en las queries del MCP mediante WHERE functional_name IN (...6 categorías...).
-- =============================================================================

DROP TABLE IF EXISTS species_traits;

CREATE TABLE species_traits (
    Species       VARCHAR(100) NOT NULL,
    functional_name VARCHAR(50)  NOT NULL,
    PRIMARY KEY (Species)
);

INSERT INTO species_traits (Species, functional_name) VALUES
('Ablennes hians',              'GenPred_schooling'),
('Abudefduf declivifrons',      'EpiBent_schooling'),
('Abudefduf troschelii',        'Plank'),
('Acanthurus nigricans',        'EpiBent_schooling'),
('Acanthurus triostegus',       'EpiBent_schooling'),
('Acanthurus xanthopterus',     'EpiBent_schooling'),
('Aluterus scriptus',           'Crip_solitary'),
('Anisotremus interruptus',     'Crip_schooling'),
('Anisotremus taeniatus',       'Crip_schooling'),
('Apogon dovii',                'Plank'),
('Apogon pacificus',            'Plank'),
('Apogon retrosella',           'Plank'),
('Arothron hispidus',           'Crip_solitary'),
('Arothron meleagris',          'Crip_solitary'),
('Aulostomus chinensis',        'GenPred_solitary'),
('Azurina atrilobata',          'Plank'),
('Balistes polylepis',          'Crip_schooling'),
('Bodianus diplotaenia',        'Crip_solitary'),
('Bothus mancus',               'GenPred_solitary'),
('Calamus brachysomus',         'Crip_solitary'),
('Calotomus carolinus',         'EpiBent_schooling'),
('Cantherhines dumerilii',      'Crip_solitary'),
('Canthigaster punctatissima',  'Crip_solitary'),
('Caranx caballus',             'Pelagic'),
('Caranx lugubris',             'Pelagic'),
('Caranx melampygus',           'GenPred_schooling'),
('Caranx sexfasciatus',         'GenPred_schooling'),
('Cephalopholis panamensis',    'GenPred_solitary'),
('Chaetodipterus zonatus',      'Crip_schooling'),
('Chaetodon humeralis',         'Crip_solitary'),
('Chanos chanos',               'Crip_solitary'),
('Chilomycterus reticulatus',   'Crip_solitary'),
('Chromis alta',                'Plank'),
('Chromis limbaughi',           'Plank'),
('Cirrhitichthys oxycephalus',  'Crip_solitary'),
('Cirrhitus rivulatus',         'GenPred_solitary'),
('Decapterus macarellus',       'Pelagic'),
('Decapterus muroadsi',         'Pelagic'),
('Dermatolepis dermatolepis',   'GenPred_schooling'),
('Elagatis bipinnulata',        'GenPred_schooling'),
('Elops affinis',               'Pelagic'),
('Epinephelus labriformis',     'GenPred_solitary'),
('Euthynnus lineatus',          'Pelagic'),
('Ferdauia orthogrammus',       'GenPred_schooling'),
('Fistularia commersonii',      'GenPred_solitary'),
('Forcipiger flavissimus',      'Crip_solitary'),
('Gnathanodon speciosus',       'GenPred_schooling'),
('Haemulon flaviguttatum',      'Crip_schooling'),
('Haemulon maculicauda',        'Crip_schooling'),
('Haemulon scudderii',          'Crip_schooling'),
('Haemulon sexfasciatum',       'Crip_schooling'),
('Haemulon steindachneri',      'Crip_schooling'),
('Halichoeres chierchiae',      'Crip_schooling'),
('Halichoeres dispilus',        'Crip_schooling'),
('Halichoeres melanotis',       'Crip_solitary'),
('Halichoeres nicholsi',        'Crip_schooling'),
('Halichoeres notospilus',      'Crip_schooling'),
('Halichoeres semicinctus',     'Crip_schooling'),
('Heteropriacanthus cruentatus','Crip_schooling'),
('Holacanthus clarionensis',    'Crip_solitary'),
('Holacanthus passer',          'EpiBent_schooling'),
('Hoplopagrus guentherii',      'GenPred_solitary'),
('Hyporthodus acanthistius',    'GenPred_solitary'),
('Johnrandallia nigrirostris',  'Crip_solitary'),
('Kyphosus azureus',            'EpiBent_schooling'),
('Kyphosus elegans',            'EpiBent_schooling'),
('Kyphosus ocyurus',            'Pelagic'),
('Kyphosus vaigiensis',         'EpiBent_schooling'),
('Lutjanus aratus',             'GenPred_schooling'),
('Lutjanus argentiventris',     'GenPred_schooling'),
('Lutjanus guttatus',           'GenPred_schooling'),
('Lutjanus inermis',            'Crip_schooling'),
('Lutjanus novemfasciatus',     'GenPred_solitary'),
('Lutjanus viridis',            'Crip_schooling'),
('Melichthys niger',            'EpiBent_schooling'),
('Microlepidotus brevipinnis',  'EpiBent_schooling'),
('Microlepidotus inornatus',    'EpiBent_schooling'),
('Microspathodon bairdii',      'Crip_solitary'),
('Microspathodon dorsalis',     'Crip_solitary'),
('Mugil cephalus',              'EpiBent_schooling'),
('Mugil curema',                'EpiBent_schooling'),
('Mulloidichthys dentatus',     'Crip_schooling'),
('Mycteroperca jordani',        'GenPred_solitary'),
('Mycteroperca prionura',       'GenPred_solitary'),
('Mycteroperca rosacea',        'GenPred_schooling'),
('Mycteroperca xenarcha',       'GenPred_solitary'),
('Myripristis berndti',         'Plank'),
('Myripristis leiognathus',     'Plank'),
('Nicholsina denticulata',      'EpiBent_schooling'),
('Novaculichthys taeniourus',   'Crip_solitary'),
('Oxycirrhites typus',          'Crip_solitary'),
('Paralabrax auroguttatus',     'Crip_solitary'),
('Paralabrax maculatofasciatus','Crip_solitary'),
('Paranthias colonus',          'Plank'),
('Pareques fuscovittatus',      'Crip_solitary'),
('Pomacanthus zonipectus',      'Crip_solitary'),
('Prionurus laticlavius',       'EpiBent_schooling'),
('Prionurus punctatus',         'EpiBent_schooling'),
('Prognathodes falcifer',       'Crip_solitary'),
('Pseudobalistes naufragium',   'Crip_solitary'),
('Sarda orientalis',            'Pelagic'),
('Sargocentron suborbitale',    'Plank'),
('Scarus compressus',           'EpiBent_schooling'),
('Scarus perrico',              'EpiBent_schooling'),
('Scomberomorus sierra',        'Pelagic'),
('Scorpaena mystes',            'Crip_schooling'),
('Scorpaenodes xyris',          'Crip_schooling'),
('Selene brevoortii',           'Crip_schooling'),
('Seriola lalandi',             'Pelagic'),
('Seriola rivoliana',           'GenPred_schooling'),
('Serranus psittacinus',        'Crip_solitary'),
('Serranus socorroensis',       'Crip_solitary'),
('Sphoeroides annulatus',       'Crip_solitary'),
('Sphoeroides lobatus',         'Crip_solitary'),
('Sphyraena ensis',             'Pelagic'),
('Sphyraena lucasana',          'Pelagic'),
('Stegastes acapulcoensis',     'EpiBent_schooling'),
('Stegastes flavilatus',        'EpiBent_schooling'),
('Stegastes rectifraenum',      'EpiBent_schooling'),
('Stethojulis bandanensis',     'Crip_solitary'),
('Sufflamen verres',            'Crip_schooling'),
('Synodus lacertinus',          'Crip_solitary'),
('Thalassoma grammaticum',      'Crip_schooling'),
('Thalassoma lucasanum',        'Plank'),
('Thalassoma virens',           'Plank');

-- Verificación rápida (correr después de la carga):
-- SELECT functional_name, COUNT(*) AS n_species
-- FROM species_traits
-- GROUP BY functional_name
-- ORDER BY functional_name;
-- Esperado: 6 categorías válidas + Pelagic (12 sp.)
